---

- name: include OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install ntp packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ ntpd_package_state }}"
  with_items: ntp_pkgs

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
   - restart ntpd
