---

- name: include OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ntp

- name: Install ntp packages
  package: name={{ ntpd_pkgs }} state={{ ntpd_pkg_state }}
  tags: ntp

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
   - restart ntpd
  tags: ntp

- name: ensure ntpd is started
  service: name={{ ntpd_svc_name }} state=started enabled=yes
  when: ntpd_enabled
  tags: ntp

- name: ensure ntpd is stopped
  service: name={{ ntpd_svc_name }} state=stopped enabled=no
  when: not ntpd_enabled
  tags: ntp
